-- 0079 — grant the `manager` role `cap.materials.manage` (operator decision, 2026-08-24).
--
-- WHY. Managers (crew leads / superintendents) hold `cap.materials.receive`, which lets them MARK
-- deliveries but not AUTHOR the list they are marking against. Every expected-materials surface
-- therefore rendered them a "Read-only here" banner, and the 2026-08-24 forensic investigation
-- into JOB-000029 (Kiwi) found that banner still directing them to per-line controls that had been
-- deleted on 2026-08-11 — a superintendent standing in front of a delivery had no in-product route
-- to correct the list in front of him. The operator's call is to give the manager tier the same
-- materials authority the office has.
--
-- ── WHAT THIS ACTUALLY OPENS — read before applying ────────────────────────────────────────────
-- `cap.materials.manage` is not scoped to the expected-materials list. Granting it to `manager`
-- also grants, to all six manager accounts at once:
--
--   1. Expected-material CRUD — add / edit / reorder / deactivate lines
--      (worker/fieldops_expected_materials.ts, four routes).
--   2. Scheduled-SHIPMENT CRUD — add / edit / remove the loads attached to a line
--      (same module, three routes).
--   3. MANIFEST IMPORT — upload, parse and COMMIT a materials manifest against a job
--      (worker/fieldops_manifests.ts `CAP_MANIFEST`). This is the highest-consequence item in
--      the list: a commit writes the job's whole BOM. (The merge path's duplicate-line defect,
--      D1, was open when this file was first written and was closed by PR #189 the same day.)
--      NOTE none of the nine manifest routes runs `requireJobScope` — see item 5.
--   4. The global MATERIAL CATALOG editor — the cross-job material TYPE vocabulary
--      (worker/fieldops_material_write.ts; SPA route `materials-catalog`, and a "Materials
--      Catalog" card appears on Home under Office operations). NOT job-scoped: an edit here is
--      visible on every job.
--   5. CROSS-JOB WRITE WITHOUT CROSS-JOB READ — the item to decide before applying this.
--
--      An EARLIER draft of this header said the grant carried a cross-job scope BYPASS on
--      expected-materials. That is no longer true and was corrected here on 2026-08-25 (audit
--      finding): the same commit that wrote this file also REMOVED `cap.materials.manage` from
--      `SCOPE_BYPASS_CAPS` (fieldops_expected_materials.ts), and rewrote the test that asserted
--      the bypass into one named "cap.materials.manage bypasses NOTHING". A manager will NOT be
--      able to READ or MARK another job's materials list — that still 403s `forbidden_job`.
--
--      What remains, and what the applying operator is actually signing off on, is an ASYMMETRY
--      that predates this migration but whose grantee set it widens. `requireJobScope` guards
--      only FOUR sites in fieldops_expected_materials.ts (the list read, receipt, flag-incident,
--      resolve-incident). It guards NONE of the seven CRUD routes — `/update`, `/seq` and
--      `/delete` take a bare line id and never see a job_id at all — and NONE of the nine routes
--      in fieldops_manifests.ts, including manifest COMMIT, which writes a job's whole BOM.
--
--      So on apply, the six manager accounts get cross-job WRITE with no cross-job READ. That is
--      not a new hole — it is the shape the capability has always had, and admins have always
--      held it — but it is the reason to decide deliberately rather than by default. The two
--      honest options: extend `requireJobScope` to those routes (a no-op for admins, who bypass
--      via `cap.jobtracker.manage`), or record a dated exception naming the asymmetry. Either
--      way it wants a cross-job WRITE test; today's JOB-B assertions are all read/receipt/flag.
--
-- What this does NOT grant: `cap.jobtracker.manage` (job/task creation), `cap.admin.*`,
-- `cap.po.manage`, `cap.payments.manage`, `cap.submit_as`. The manager tier stays out of
-- procurement, payments, account administration and impersonation.
--
-- NO ORDER DEPENDENCY. Unlike 0023/0013, this migration adds no column and no vocabulary the
-- Worker must already parse — `cap.materials.manage` has been a live capability since 0013 and
-- every gate that reads it already ships. Applying before or after a deploy is equally safe, and
-- `resolveCapabilities` reads `role_capabilities` per request, so the grant takes effect on the
-- next request each manager makes. No re-login, no session-epoch bump, no per-account backfill:
-- capabilities are derived from the role, so every existing manager account picks this up whenever
-- it was created.
--
-- TO REVERSE:
--   DELETE FROM role_capabilities
--    WHERE role_key = 'manager' AND capability_key = 'cap.materials.manage';
--
-- Enumerated explicitly (NOT `SELECT … FROM capabilities`) so the grant is exact and auditable —
-- the 0023 posture. INSERT OR IGNORE so re-applying the seed portion is safe.

INSERT OR IGNORE INTO role_capabilities (role_key, capability_key) VALUES
  ('manager', 'cap.materials.manage');
